### ISSUE TITLE
Error: Cannot find module '../build/Release/wrtc.node'

### ISSUE THREAD

**Issue by IbrH** [geckosio/phaser3-multiplayer-game-example#3]
$ node ./server/server.js
```
internal/modules/cjs/loader.js:964
    throw err;
    ^

Error: Cannot find module '../build/Release/wrtc.node'
Require stack:
- /home/hhm/Dokumente/Phaser Projects/phaser3-multiplayer-game/node_modules/wrtc/lib/binding.js
- /home/hhm/Dokumente/Phaser Projects/phaser3-multiplayer-game/node_modules/wrtc/lib/index.js
- /home/hhm/Dokumente/Phaser Projects/phaser3-multiplayer-game/node_modules/@geckos.io/server/lib/wrtc/webrtcConnection.js
- /home/hhm/Dokumente/Phaser Projects/phaser3-multiplayer-game/node_modules/@geckos.io/server/lib/wrtc/connectionsManager.js
- /home/hhm/Dokumente/Phaser Projects/phaser3-multiplayer-game/node_modules/@geckos.io/server/lib/server.js
- /home/hhm/Dokumente/Phaser Projects/phaser3-multiplayer-game/node_modules/@geckos.io/server/lib/index.js
- /home/hhm/Dokumente/Phaser Projects/phaser3-multiplayer-game/server/game/gameScene.js
- /home/hhm/Dokumente/Phaser Projects/phaser3-multiplayer-game/server/game/config.js
- /home/hhm/Dokumente/Phaser Projects/phaser3-multiplayer-game/server/game/game.js
- /home/hhm/Dokumente/Phaser Projects/phaser3-multiplayer-game/server/server.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:961:17)
    at Function.Module._load (internal/modules/cjs/loader.js:854:27)
    at Module.require (internal/modules/cjs/loader.js:1023:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/home/hhm/Dokumente/Phaser Projects/phaser3-multiplayer-game/node_modules/wrtc/lib/binding.js:6:20)
    at Module._compile (internal/modules/cjs/loader.js:1128:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)
    at Module.load (internal/modules/cjs/loader.js:983:32)
    at Function.Module._load (internal/modules/cjs/loader.js:891:14)
    at Module.require (internal/modules/cjs/loader.js:1023:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/hhm/Dokumente/Phaser Projects/phaser3-multiplayer-game/node_modules/wrtc/lib/binding.js',
    '/home/hhm/Dokumente/Phaser Projects/phaser3-multiplayer-game/node_modules/wrtc/lib/index.js',
    '/home/hhm/Dokumente/Phaser Projects/phaser3-multiplayer-game/node_modules/@geckos.io/server/lib/wrtc/webrtcConnection.js',
    '/home/hhm/Dokumente/Phaser Projects/phaser3-multiplayer-game/node_modules/@geckos.io/server/lib/wrtc/connectionsManager.js',
    '/home/hhm/Dokumente/Phaser Projects/phaser3-multiplayer-game/node_modules/@geckos.io/server/lib/server.js',
    '/home/hhm/Dokumente/Phaser Projects/phaser3-multiplayer-game/node_modules/@geckos.io/server/lib/index.js',
    '/home/hhm/Dokumente/Phaser Projects/phaser3-multiplayer-game/server/game/gameScene.js',
    '/home/hhm/Dokumente/Phaser Projects/phaser3-multiplayer-game/server/game/config.js',
    '/home/hhm/Dokumente/Phaser Projects/phaser3-multiplayer-game/server/game/game.js',
    '/home/hhm/Dokumente/Phaser Projects/phaser3-multiplayer-game/server/server.js'
  ]
}
```

$ node -v
v13.3.0

OS:
Ubuntu 19.04

**Comment by yandeu** [comment]
Have you tried node v12?

Geckos.io targets only versions 8, 10, 11 and 12.

`"node": "^8 || ^10 || ^11 || ^12"`

**Comment by IbrH** [comment]
I did and it didn't work, but I'm using a different pc right now and it works there so I'm closing this.

**Comment by ouya99** [comment]
out of nowhere i am having the same issue today. Just re-started my server.. no changes to server.js
it seems it accessed some build in the main project (node_modules) and I had rebuilt with node 11.
